dist: xenial

services:
  - docker

language: python

python: 3.6

before_install:
  - docker-compose -v
  - docker -v

matrix:
  include:
    - name: Docker
      script: sh tests/test_docker.sh

install:
  - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: aAj5AfBuTOl63+6511BtEpMny11bE9xQEXpbWr4mbp5TCUphJXqMK2eHUitgdsIVIxeDMwUyUKmyQcwVkAqJZa95XL/Zr87pto/KlSFZ3wDOgYMcZVhfl2B5rciUegpbwD4Sb1qP3Rv32YUH+36X1kQY3VO3G/i7Vk+J7rWS/1yzFS1BZk1kqBa7dWf05H4iaz8kcYneXTdYH18iCEcsM+BfXEwFeqgqVKyxwRubw+7oMVFMTPWuzI1YyuD44oXZE3LmDD8KricqeMBU+Vy+xz/XdaDvBF3eywbJAB6PsHzCTYMXndNocwH004c3TMz5RKl8gROIf9wuWrlldhgn3vmVIguECOOlP65WUCGGVqC1/tBO1aDXI9P24E5PlliwF6B2JsOKIGRwWtVqSI5eC73ygW/wVm3lNp6K8ifG72OdrZtGDh7Q/HwaSO7kmDjMtvyFebpENgXJtSVzs6AcPgnFVf8S/GaqDvOTQ3R7yQqKctFZcjYZvfFG9ThaXJF7p5usmEaDim8LdmyTgDbIbBiwycUvzuJ6jkBhGaZ5cPuN8jPKOKq5dEPEWUXBrrVEbADlozfcH1/G5wV09vFkQ4AFrBSOuLUOH3c3QJOrLbyQ1clfqv5dAPOmZK0GGfDtFW3HtjDy7k2ix3c2zdUBB4v24W71OJ/2a0aEQBAtHYw=
    on_success: change
    on_failure: always
