services:
  - type: web
    name: openfootprint-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: openfootprint-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

  - type: web
    name: openfootprint-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: openfootprint-backend/*
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: openfootprint-db
    databaseName: openfootprint
    user: openfootprint_user
